# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# What combinations to test
environment:
  matrix:
    - nodejs_version: 12
    - nodejs_version: 10

version: "{build}"
build: false
deploy: false

branches:
  only:
    - master

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@latest
  - npm ci

test_script:
  - node --version
  - npm --version
  - npm run test

matrix:
  fast_finish: true # set this flag to immediately finish build once one of the jobs fails.
